### ISSUE TITLE
Mod not being loaded

### ISSUE THREAD

**Issue by MrSamoloth** [Amands2Mello/AmandsGraphics#2]
The mod is installed properly and is in the right folder. The aki server isn't even detecting it but it is detecting another mod (Image below)
![image](https://github.com/Amands2Mello/AmandsGraphics/assets/72635261/6a1ca4f8-5599-4f01-aa57-c3d3082c75af)
I am using a save file from the bleeding edge version of spt that i played on until official release
below is a screenshot with the F12 menu open showing no amands graphics settings
![image](https://github.com/Amands2Mello/AmandsGraphics/assets/72635261/b25503bf-4557-49ef-92c0-0bd0f67ab368)

**Comment by Amands2Mello** [comment]
graphics mod version 1.6.0 is only for SPT-AKI 3.8.0 release, older versions of 3.8.0 bleeding edge won't work

**Comment by MrSamoloth** [comment]
> graphics mod version 1.6.0 is only for SPT-AKI 3.8.0 release, older versions of 3.8.0 bleeding edge won't work

Yeah I know, I was running 3.8.0 release you can see that in the screenshot. I don't know what the issue was, reinstalling SPT 3 times worked I have no idea what caused it but maybe because on the day I downloaded the installer SPT servers were struggling so maybe the install got corrupted causing this. Don't know don't care, it fixed itself
